### ISSUE TITLE
DEPTH_ZERO_SELF_SIGNED_CERT

### ISSUE THREAD

**Issue by strk** [SaltwaterC/http-request#32]
I'm getting DEPTH_ZERO_SELF_SIGNED_CERT errors despite using "noSslValidation" option:

```
      http.get({                                                      
                    url : tiles_url,                                            
                    // We don't need ssl validation during tests                
                    noSslValidation : true                                      
                }, ...
```

The stack trace:

```
     Error: DEPTH_ZERO_SELF_SIGNED_CERT                                         
      at SecurePair.<anonymous> (tls.js:1370:32)                                
      at SecurePair.maybeInitFinished (tls.js:982:10)                           
      at CleartextStream.read [as _read] (tls.js:469:13)                        
      at CleartextStream.Readable.read (_stream_readable.js:320:10)             
      at EncryptedStream.write [as _write] (tls.js:366:25)                      
      at doWrite (_stream_writable.js:226:10)                                   
      at writeOrBuffer (_stream_writable.js:216:5)                              
      at EncryptedStream.Writable.write (_stream_writable.js:183:11)            
      at write (_stream_readable.js:583:24)                                     
      at flow (_stream_readable.js:592:7)                                       
      at Socket.pipeOnReadable (_stream_readable.js:624:5)                      
      at emitReadable_ (_stream_readable.js:408:10)                             
      at emitReadable (_stream_readable.js:404:5)                               
      at readableAddChunk (_stream_readable.js:165:9)                           
      at Socket.Readable.push (_stream_readable.js:127:10)                      
      at TCP.onread (net.js:528:21)                          
```

I've also exported NODE_TLS_REJECT_UNAUTHORIZED=0 but have the same problem.

Node version is v0.10.26

**Comment by SaltwaterC** [comment]
Hi. Is the URL relevant, or can it be reproduced with any self-sign cert?

**Comment by strk** [comment]
I think it can be reproduced, looking here: https://github.com/request/request/issues/418 -- but I didnt' test myself

**Comment by SaltwaterC** [comment]
Yep, bad documentation is bad. Sorry about that. Dropped the ball white writing the jsdoc block. The source code reads:

``` javascript
        if (this.options.noSslVerifier !== true) {
            this.reqOpt.rejectUnauthorized = true;
        } else {
            this.reqOpt.rejectUnauthorized = false;
        }
```

The correct option key is _noSslVerifier_. Can you please recheck if it works with this option?

**Comment by strk** [comment]
noSslVerifier sems to work
